## Matrix operations using numpy

In [1]:
## Import necessary libraries
import numpy as np

In [3]:
## Define the matrices
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8,9], [10,11,12]])

In [4]:
## Matrix Addition
C = A + B
print("Matrix Addition:\n", C)

Matrix Addition:
 [[ 8 10 12]
 [14 16 18]]


In [5]:
## Matrix Subtraction
D = A - B
print("Matrix Subtraction:\n", D)

Matrix Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
